name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Cache
        uses: actions/cache@v2

      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew ktlintCheck

  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Cache
        uses: actions/cache@v2

      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

  ui-test:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        api-level: [22, 24, 26, 28, 30]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Gradle Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      # API 30+ emulators only have Google API system images.
      - name: Get AVD target
        uses: ./.github/actions/get-avd-target
        id: avd-target
        with:
          api-level: ${{ matrix.api-level }}

      - name: AVD Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ steps.avd-target.outputs.target }}-${{ matrix.api-level }}

      - name: Create AVD & generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2.20.0
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ steps.avd-target.outputs.target }}
          disable-animations: false
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: echo "Generated AVD Snapsho for Caching."

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: UI Test
        uses: reactivecircus/android-emulator-runner@v2.20.0
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ steps.avd-target.outputs.target }}
          disable-animations: true
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: bash ./gradlew connectedDebugAndroidTest

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Cache
        uses: actions/cache@v2

      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug
        run: bash ./gradlew ":app:assembleDebug"

      - name: Upload a Build Artifact APK
        uses: actions/upload-artifact@v2.2.4
        with:
          name: debug-babbab.zip
          path: app/build/outputs/apk/debug
